import IMDB_file                # Import IMDb_file class objects
import FamousBirthday_file      # Import FamousBirthday_data class objects
import pandas as pd
import matplotlib.pyplot as plt # To Plot the graphs

## Read the csv files generated by calling IMDB_file and  FamousBirthday_file
imdb_df = pd.read_csv("imdb.csv")

famous_df = pd.read_csv("FamousBirthdays.csv")
# print(famous_df.head())

## Merge the datasets using Inner Join to extract common celebrity names
df1 = pd.merge(imdb_df, famous_df, on='Name', how='inner')
print(df1)

## Plot the graph
df1.plot.bar(x='Name', rot=0, figsize=(15,10), fontsize=12,title = 'Difference in rankings of the Celebrities from the two websites')
plt.show()

# df2 = pd.merge(imdb_df, famous_df, on='Name', how='outer')
# print(df2)
# df2.plot.pie(y='Name', figsize=(5, 5))
# plt.show()

